# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/cfultz"

[social.params]
icon = "fa-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.social/@cfultz"

[social.params]
icon = "fa-mastodon"

[[social]]
identifier = "steam"
name = "Steam"
url = "https://steamcommunity.com/id/thesippycup/"

[social.params]
icon = "fa-steam"

[[social]]
identifier = "archidekt"
name = "Archidekt"
url = "https://archidekt.com/u/cfultz/"


[social.params]
icon = "purple-archidekt"
