# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/cfultz"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Twitter"
url = "https://mastodon.social/@cfultz"

[social.params]
icon = "fa-brands fa-astodon"
